Onlineplatform/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

apps/courses/models.py
from datetime import datetime


from django.db import models

# Create your models here.


class Course(models.Model):
    name = models.CharField(max_length=50, verbose_name='course name')
    desc = models.CharField(max_length=300, verbose_name='course description')
    detail = models.TextField(verbose_name="course detail")  # infinite length
    degree = models.CharField(choices=(('beginner', 'beginner'),('intermediate', 'intermediate'), ('advanced', 'advanced')),max_length=10)
    learn_times = models.IntegerField(default=0,verbose_name='learning time (min)')
    student = models.IntegerField(default=0, verbose_name='student number')
    fav_nums = models.IntegerField(default=0, verbose_name='favorite number')
    image = models.ImageField(upload_to='courses/%Y/%m', verbose_name='cover image', max_length=100)
    click_num = models.IntegerField(default=0, verbose_name='course click')
    add_time = models.DateTimeField(default=datetime.now, verbose_name= 'add time')

    class Meta:
        verbose_name = 'course'
        verbose_name_plural = verbose_name


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name='course', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name='lesson name')
    add_time = models.DateTimeField(default=datetime.now, verbose_name= 'add time')

    class Meta:
        verbose_name = 'course lesson'
        verbose_name_plural = verbose_name


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name='lesson',on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name='video name')
    add_time = models.DateTimeField(default=datetime.now, verbose_name= 'add time')

    class Meta:
        verbose_name = 'course video'
        verbose_name_plural = verbose_name


class CourseRecourse(models.Model):
    course = models.ForeignKey(Course, verbose_name='course',on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name='course resource name')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='add time')
    download = models.FileField(upload_to='course/resource/%Y/%m', verbose_name='resource file', max_length=100)

    class Meta:
        verbose_name = 'course resources'
        verbose_name_plural = verbose_name

apps/organization/models.py
from datetime import datetime
from django.db import models
from DjangoUeditor.models import UEditorField

# Create your models here.


class CityDict(models.Model):
    name = models.CharField(max_length=20, verbose_name='city name')
    desc = models.CharField(max_length=200, verbose_name='city description')
    add_time = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name = 'city'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class CourseOrg(models.Model):
    name = models.CharField(max_length=50, verbose_name= 'organization name')
    desc = models.TextField(verbose_name='organization description', default='')

    tag = models.CharField(default='Famous', max_length=10, verbose_name='Organization tag')
    category = models.CharField(default='Organization', verbose_name='organization category', max_length=20 ,
                                choices=(('Organization','Organization'),('University','University'),('Person','Person')))
    click_num = models.IntegerField(default=0 , verbose_name='click number')
    fav_nums = models.IntegerField(default=0, verbose_name='favorite number')
    image = models.ImageField(upload_to='org/%Y/%m', max_length=100, verbose_name='logo')
    address = models.CharField(max_length=300, verbose_name='organization address')
    city = models.ForeignKey(CityDict, verbose_name='organization city',on_delete=models.CASCADE)
    students =models.IntegerField(default=0 , verbose_name='student number')
    course_num =models.IntegerField(default=0, verbose_name='course number')
    add_time = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name = 'organization'
        verbose_name_plural = verbose_name

    def get_teacher_nums(self):
        return self.teacher_set.all().count()

    def __str__(self):
        return self.name


class Teacher(models.Model):
    org = models.ForeignKey(CourseOrg,default='',verbose_name='work organization',on_delete=models.CASCADE)
    name = models.CharField(max_length=50, default='',verbose_name='teacher name')
    work_years = models.IntegerField(default=0, verbose_name='work years')
    work_company = models.CharField(default='', max_length=50, verbose_name='work company')
    work_position = models.CharField(default='', max_length=40, verbose_name='work position')
    points = models.CharField(default='',max_length=50, verbose_name='teaching points')
    click_num = models.IntegerField(default=0, verbose_name='click number')
    fav_nums = models.IntegerField(default=0, verbose_name='favorite number')
    age = models.IntegerField(default=20, verbose_name="age")
    image = models.ImageField(default='', upload_to="teacher/%y/%m", verbose_name="user image", max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='time of adding')

    class Meta:
        verbose_name = 'teacher'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def get_course_nums(self):
        return self.course_set.all().count()

apps/organization/views.py
from django.shortcuts import render
from django.views.generic import View
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.db.models import Q

from .models import CourseOrg, CityDict, Teacher
from .forms import UserAskForm
from operation.models import UserFavorite
from courses.models import Course
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class OrgView(View):
    """
       课程机构列表功能
       """

    def get(self, request):
        # 课程机构
        all_orgs = CourseOrg.objects.all()
        hot_orgs = all_orgs.order_by("-click_nums")[:3]

        # 城市
        all_citys = CityDict.objects.all()

        # 机构搜索
        search_keywords = request.GET.get('keywords', "")
        if search_keywords:
            all_orgs = all_orgs.filter(Q(name__icontains=search_keywords) | Q(desc__icontains=search_keywords))

        # 取出筛选城市
        city_id = request.GET.get('city', "")
        if city_id:
            all_orgs = all_orgs.filter(city_id=int(city_id))

        # 类别筛选
        category = request.GET.get('ct', "")
        if category:
            all_orgs = all_orgs.filter(category=category)

        sort = request.GET.get('sort', "")
        if sort:
            if sort == "students":
                all_orgs = all_orgs.order_by("-students")
            elif sort == "courses":
                all_orgs = all_orgs.order_by("-course_nums")

        org_nums = all_orgs.count()

        # 对课程机构进行分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        p = Paginator(all_orgs, 5, request=request)

        orgs = p.page(page)
        return render(request, "org-list.html", {
            "all_orgs": orgs,
            "all_citys": all_citys,
            "org_nums": org_nums,
            "city_id": city_id,
            "category": category,
            "hot_orgs": hot_orgs,
            "sort": sort
        })


class AddUserAskView(View):
    def post(self,request):
        userask_form = UserAskForm(request.POST)
        if userask_form.is_valid():
            user_ask = userask_form.save(commit = True)
            return HttpResponse({"status":"success"},content_type='application.json')
        else:
            return HttpResponse({"status":"fail","msg":"wrong"}, content_type='application/json')


class OrgHomeView(View):
    def get(self, request, org_id):
        current_page = 'home'
        course_org = CourseOrg.objects.get(id = int(org_id))
        course_org.click_num += 1
        course_org.save()
        has_fav = False
        if request.user.is_authenticated():
            if UserFavorite.objects.filter(user = request.user, fav_id = course_org.id, fav_type = 2):
                has_fav = True

        all_courses = course_org.course_set.all()[:3]
        all_teachers = course_org.teacher_set.all()[:1]
        return render(request, 'org-detail-homepage.html', {
            'all_courses': all_courses,
            'all_teachers': all_teachers,
            'course_org': course_org,
            'current_page': current_page,
            'has_fav': has_fav
        })


class OrgCourseView(View):
    def get(self, request, org_id):
        current_page = "course"
        course_org = CourseOrg.objects.filter(id=int(org_id))
        has_fav = False
        if request.user.is_authenticated():
            if UserFavorite.objects.filter(user = request.user, fav_id=course_org.id, fav_type = 2):
                has_fav = True
        all_courses = course_org.course_set.all()
        return render(request, 'org-detail-course.html', {
            "all_courses": all_courses,
            "course_org": course_org,
            "current_page": current_page,
            'has_fav':has_fav,
        })

class OrgDescView(View):
    def get(self, request, course_id):
        current_page = 'decs'
        course_org = CourseOrg.objects.filter(id = int(course_id))
        has_fav = False
        if request.user.is_authenticated():
            if UserFavorite.objects.filter(user = request.user, fav_id = course_id, fav_type =2):
                has_fav = True
        return render(request, 'org-detail-desc.html',{
            'current_page': current_page,
            'course_org': course_org,
            'has_fav':has_fav,
        })


class OrgTeacherView(View):
    def get(self, request, org_id):
        current_page = 'teacher'
        course_org = CourseOrg.objects.filter(id=int(org_id))
        has_fav = False
        if request.user.is_authenticated():
            if UserFavorite.objects.filter(user = request.user, fav_id=org_id, fav_type=2):
                has_fav = True
        all_teachers = course_org.teacher_set.all()
        return render(request, 'org-detail-teachers.html', {
            "all_teachers":all_teachers,
            "course_org":course_org,
            "current_page":current_page,
            "has_fav":has_fav,
        })

class AddFavView(View):
    def post(self, request):
        fav_id = request.POST.get('fav_id', 0)
        fav_type = request.POST.get('fav_type', 0)

        if not request.user.is_authenticated():
            return HttpResponse({'status':'fail','msg':'User does not login'},content_type='application/json')
        exist_records = UserFavorite.objects.filter(user = request.user, fav_id = int(fav_id), fav_type= int(fav_type))
        if exist_records:
            exist_records.delete()
            if int(fav_type) ==1:
                course = Course.objects.get(id = int(fav_id))
                course.fav_nums -= 1
                if course.fav_nums < 0:
                    course.fav_nums = 0
                course.save()
            elif int(fav_type) == 2:
                course_org = CourseOrg.objects.get(id = int(fav_id))
                course_org.fav_nums -= 1
                if course_org.fav_nums <0:
                    course_org.fav_nums = 0
                course_org.save()
            elif int(fav_type)== 3:
                teacher = Teacher.objects.get(id = int(fav_id))
                teacher.fav_nums -=1
                if teacher.fav_nums <0:
                    teacher.fav_nums = 0
                teacher.save()
            return HttpResponse('{"status":"success", "msg":"favorite"}', content_type='application/json')
        else:
            user_fav = UserFavorite()
            if int(fav_id)>0 and int(fav_type)>0:
                user_fav.user = request.user
                user_fav.fav_id = int(fav_id)
                user_fav.fav_type = int(fav_type)
                user_fav.save()

                if int(fav_type) == 1:
                    course = Course.objects.get(id = int(fav_id))
                    course.fav_nums += 1
                    course.save()
                elif int(fav_type) == 2:
                    course_org = CourseOrg.objects.get(id = int(fav_id))
                    course_org.fav_nums += 1
                    course_org.save()
                elif int(fav_type) == 3:
                    teacher = Teacher.objects.get(id = int(fav_id))
                    teacher.fav_nums += 1
                    teacher.save()
                return HttpResponse('{"status":"success", "msg":"Already added"}', content_type='application/json')
            else:
                return HttpResponse('{"status":"success", "msg":"Error"}', content_type='application/json')


class TeacherListView(View):
    def get(self, request):
        all_teachers = Teacher.objects.all()
        search_keywords = request.GET.get('keywords',"")
        if search_keywords:
            all_teachers = all_teachers.filter(Q(name__icontains=search_keywords)|
                                               Q(work_company__icontains=search_keywords)|
                                               Q(work_position_icontains=search_keywords))
        sort = request.GET.get('sort', '')
        if sort:
            if sort == "hot":
                all_teachers = all_teachers.order_by('-click_nums')
        sorted_teacher = Teacher.objects.all().order_by('-click_nums')[:3]

        try:
            page = request.GET.get('page','')
        except PageNotAnInteger:
            page = 1

        p = Paginator(all_teachers, 1, request = request)
        teachers = p.page(page)
        return request(request,'teachers-list.html',{
            "all_teachers": teachers,
            "sorted_teacher": sorted_teacher,
            "sort": sort,
        })


class TeacherDetailView(View):
    def get(self,request, teacher_id):
        teacher = Teacher.objects.filter(id=int(teacher_id))
        teacher.click_num += 1
        teacher.save()
        all_courses = Course.objects.filter(teacher=teacher)

        has_teacher_faved = False
        if request.user.is_authenticated():
            if UserFavorite.objects.filter(user = request.user, fav_type = 3, fav_id = teacher.id):
                has_teacher_faved = True

        has_org_faved = False
        if request.user.is_authenticated():
            if UserFavorite.objects.filter(user=request.user, fav_type=3, fav_id=teacher.org.id):
                has_org_faved = True

        sorted_teacher = Teacher.objects.all().order_by('-click_nums')[:3]
        return render(request, 'teacher-detail.html',{
            "teacher": teacher,
            "all_courses": all_courses,
            "sorted_teacher": sorted_teacher,
            "has_teacher_faved": has_teacher_faved,
            "has_org_faved": has_org_faved
        })

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/course-comment.html
{% extends 'base.html' %}
{% block title %}公开课评论 - 慕学在线网{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="/">首页</a>></li>
                <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
				<li><a href="{% url 'course:course_detail' course.id %}">课程详情</a>></li>
                <li>课程评论</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/course-comment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
{% endblock %}

{% block content %}
    <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_times }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
            <div class="content-wrap clearfix">
                <div class="content">
                    <div class="mod-tab-menu">
                        <ul class="course-menu clearfix">
                            <li><a class="ui-tabs-active " id="learnOn"  href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
                            <li><a id="commentOn" class="active" href="{% url 'course:course_comments' course.id %}"><span>评论</span></a></li>
                        </ul>
                    </div>

                    <!--发布评论-->
                    <div id="js-pub-container" class="issques clearfix js-form">
                        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！" ></textarea>
                        </div>
                        <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                        <p class="global-errortip js-global-error"></p>
                    </div>
                    <div id="course_note">
                        <ul class="mod-post" id="comment-list">
                            {% for user_comments in all_comments %}
                            <li class="post-row">
                                <div class="media">
                                    <span target="_blank"><img src='{{ MEDIA_URL }}{{ user_comments.user.image }}' width='40' height='40' /></span>
                                </div>
                                <div class="bd">
                                    <div class="tit">
                                        <span target="_blank">{{ user_comments.user.username }}</span>
                                    </div>
                                    <p class="cnt">{{ user_comments.comments }}</p>
                                    <div class="footer clearfix">
                                        <span title="创建时间" class="l timeago">时间：{{ user_comments.add_time }}</span>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>

                </div>
                <div class="aside r">
                    <div class="bd">

                        <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for course_resource in course_resources %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ course_resource.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ course_resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                        <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                            <span class="job">{{ course.teacher.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.youneed_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_tell }}</dd>
                            </dl>
                        </div>
                    </div>


                        <div class="cp-other-learned  js-comp-tabs">
                            <div class="cp-header clearfix">
                                <h2 class="cp-tit l">该课的同学还学过</h2>
                            </div>
                            <div class="cp-body">
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                    <!-- img 200 x 112 -->
                                    <ul class="other-list">
                                        <li class="curr">
                                            <a href="/view/85?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/57035ff200014b8a06000338-240-135.jpg" alt="Java入门第一季">
                                                <span class="name autowrap">Java入门第一季</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/view/110?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/5703604a0001694406000338-240-135.jpg" alt="Java入门第三季">
                                                <span class="name autowrap">Java入门第三季</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/view/124?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/570360620001390f06000338-240-135.jpg" alt="Java入门第二季">
                                                <span class="name autowrap">Java入门第二季</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/view/47?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/570765d90001bf1406000338-240-135.jpg" alt="Spring MVC起步">
                                                <span class="name autowrap">Spring MVC起步</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/view/36?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/53e1d0470001ad1e06000338-240-135.jpg" alt="JavaScript入门篇">
                                                <span class="name autowrap">JavaScript入门篇</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                    <ul class="other-list">
                                        <li class="curr">
                                            <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                                <span class="name autowrap">Java工程师</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>    </div>
            </div>
            <div class="clear"></div>

        </div>

    </div>
</div>
{% endblock %}

{% block custom_js %}
<script type="text/javascript">
    //添加评论
    $('#js-pl-submit').on('click', function(){
        var comments = $("#js-pl-textarea").val()
        if(comments == ""){
            alert("评论不能为空")
            return
        }
        $.ajax({
            cache: false,
            type: "POST",
            url:"{% url 'course:add_comment' %}",
            data:{'course_id':{{ course.id }}, 'comments':comments},
            async: true,
            beforeSend:function(xhr, settings){
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function(data) {
                if(data.status == 'fail'){
                    if(data.msg == '用户未登录'){
                        window.location.href="/login/";
                    }else{
                        alert(data.msg)
                    }

                }else if(data.status == 'success'){
                    window.location.reload();//刷新当前页面.
                }
            },
        });
    });

</script>
{% endblock %}

templates/course-list.html
{% extends 'base.html' %}
{% block title %}公开课列表 - 慕学在线网{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
    <section>
	<div class="wp">
		<div class="list" style="margin-top:0;">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li {% if sort == '' %}class="active"{% endif %}><a href="?sort=">最新 </a></li>
						<li {% if sort == 'hot' %}class="active"{% endif %}><a href="?sort=hot">最热门</a></li>
						<li {% if sort == 'students' %}class="active"{% endif %}><a href="?sort=students">参与人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					<div class="group_list">
                        {% for course in all_courses.object_list %}
                            <div class="box">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="280" height="350" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id %}">
                                        <h2>{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href="{% url 'course:course_detail' course.id %}"><span class="fl">来自{{ course.course_org.name }}</span></a>
                                    <span class="star fr  notlogin
                                        " data-favid="15">
                                        {{ course.fav_nums }}
                                    </span>
                                </div>
                            </div>
                        {% endfor %}


					</div>
                    <div class="pageturn">
                        <ul class="pagelist">
                            {% if all_courses.has_previous %}
                                <li class="long"><a href="?{{ all_courses.previous_page_number.querystring }}">上一页</a></li>
                            {% endif %}

                            {% for page in all_courses.pages %}
                                {% if page %}
                                    {% ifequal page all_courses.number %}
                                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                    {% else %}
                                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                    {% endifequal %}
                                {% else %}
                                    <li class="none"><a href="">...</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if all_courses.has_next %}
                                <li class="long"><a href="?{{ all_courses.next_page_number.querystring }}">下一页</a></li>
                            {% endif %}

                        </ul>
                    </div>
				</div>
                </div>
			</div>
			<div class="right layout">
				<div class="head">热门课程推荐</div>
				<div class="group_recommend">
                    {% for hot_course in hot_courses %}
                    <dl>
						<dt>
							<a target="_blank" href="{{ ecmall_ad.url }}">
								<img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ hot_course.image }}"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href="{{ ecmall_ad.url }}"><h2> {{ hot_course.name }}</h2></a>
							<span class="fl">难度：<i class="key">{{ hot_course.get_degree_display }}</i></span>
						</dd>
					</dl>
                    {% endfor %}


				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}